### PR TITLE
Attempt to fix #11

### LINKED ISSUE #11: heading-like lines inside fenced blocks or comments
Lines that start with `#` inside of fenced blocks and comments act like real headings. These should not fold and unfold the text that's below the "phantom" headings. Here is an example:

``````
# test heading

hello world

## a second heading

```
# a phantom heading
a: 2
```

more text

# another heading

words...

<!--  
# another phantom heading
this is a comment
-->

# a final heading
``````

One way to fix this might be to include an additional check when checking if a line is a header. Maybe check the class of the line to make sure it isn't "comment block gfm" or "markup".

### PR DESCRIPTION
**Pull request by tshort**
This attempts to identify and skip headings in comment or fenced code blocks.

### CODE REVIEW

**Comment by melke** [comment]
Thanks @tshort The last two spec tests do not pass:
screen shot 2015-10-25 at 22 06 04

**Comment by tshort** [comment]
@melke , any idea what's wrong with the specs? It seems to work right when playing with that file. 

Any tips on debugging spec files?

**Comment by melke** [comment]
@tshort  It's really strange that the line counting doesn't work in those spec tests. As you say, the functionality seems to work flawlessly when not run in spec context. Could it be that some folding-within-folding confuses the line counting functions in Atom? I would like to see the specs pass, though, mainly for regression testing in the future when new functionality is added. (The code is getting a bit complex). I'll try to find another way of doing the expect checks, other than line counting. If you have any ideas, feel free to push into this PR.

**Comment by tshort** [comment]
I'm stumped. I tried playing around with the debugger. The problem is, you can't "see" the buffer under test that's being manipulated. There's probably something different about how it treats the scope lookup when in "test mode".

If we can't think of anything, I suggest we comment out the tests.

**Comment by tshort** [comment]
Discussion posted:

https://discuss.atom.io/t/spec-fails-but-works-right-in-editor/22064

**Comment by tshort** [comment]
@melke, do you know how to do this?

https://discuss.atom.io/t/spec-fails-but-works-right-in-editor/22064/7?u=tshort

**Comment by tshort** [comment]
Tests run now! Discuss user "abe" figured it out. See the discussion link above.

**Comment by melke** [comment]
Thank you @tshort 
It works great!

**Comment by melke** [comment]
Hi @tshort I couldn't find a better way to contact you besides through this PR :)

I'm wondering if you would be interested in taking over as the maintainer of the markdown-folder package? The thing is that I have completely stopped using Atom and hence markdown-folder myself. For various reasons, I am using emacs for everything nowadays. I feel that you would be a much better maintainer, since you actually have created the most advanced features in the package. Would you be interested in being the maintainer?

**Comment by tshort** [comment]
Yes, I can do that, Mats...

**Comment by melke** [comment]
Thank you Tom! That's great! As I understand it, the only things needed for the transfer is to transfer ownership of the github repo and then update the package.json when publishing the package to Atom. (According to this discussion: https://discuss.atom.io/t/need-maintainers-for-some-projects/13850 

I'll transfer the repo to you then. Good luck with the development in the future!

**Comment by melke** [comment]
Hi again @tshort I tried to transfer the repo, but your forked copy with the same name is blocking the transfer. Could you please remove or rename the forked repo?

**Comment by tshort** [comment]
I deleted  my forked repo...

**Pull request merged**
