### PR TITLE
Add cycling like org-mode

### PR DESCRIPTION
**Pull request by tshort**
This PR implements cycling something like org-mode. `cycle` is like `toggle`, but it cycles between "Collapse all", "Show headings", and "Show all". `cycleall` does this globally.

I added tests, but none of the package tests work on my windows machine (probably user error).

Org-mode attaches these functions to TAB and SHIFT-TAB in a DWIM fashion. I didn't attempt that.

### CODE REVIEW

**Comment by tshort** [comment]
Here are the keys I use with vim-mode:

``` cson
'atom-text-editor.vim-mode.normal-mode':
  'tab': 'markdown-folder:cycle'
  'shift-tab': 'markdown-folder:cycleall'
```

**Comment by tshort** [comment]
I've updated this pull request to add a feature to fold and unfold fenced code blocks. I've also included `dwim-toggle` to toggle or cycle the folding of either headings or code blocks, depending on context. This works well with the TAB key; when you hit TAB at any place but a heading or the first line of a code block, you get standard TAB-key behavior.

The folding of code blocks works well with [mdpad](https://github.com/tshort/mdpad/tree/gh-pages), a system I put together to make web apps by mixing Markdown with code and data in fenced code blocks. See [here](http://distributionhandbook.com/calculators/) for more examples.

**Comment by tshort** [comment]
The README now includes the following video:

Folding in action

**Comment by tshort** [comment]
Pinging @melke ...

**Comment by melke** [comment]
Thank you @tshort 
Accidently, I had "unwatched" this repo in Github, that's why my response is so late.

This looks great! I love org-mode. Actually, the reason for writing this plugin in the first place was to get some org-mode-like behavior for markdown.
I haven't looked at the code and done any tests yet, though. Give me a couple of days and I will get back to you.

**Comment by melke** [comment]
Hi @tshort Your cycle addition works (almost) perfectly! Thank you. There is one small thing that is not working when doing cycleall: If there is no H1 headers, the cycling doesn't work. I've added a spec test that tests against a file that does not have a H1 header, but I thought I'd leave the fix to you :) It would also be great if you could add spec tests for toggling code blocks. Maybe in another spec file? 
Please have a look at my branch https://github.com/melke/markdown-folder/tree/tshort-master , where I made the changes.

**Comment by melke** [comment]
@tshort Oops, it's checked in now

**Pull request merged**
